[build]
  publish = "dist"
  command = "npm install --include=dev && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
